### ISSUE TITLE
client secret

### ISSUE THREAD

**Issue by lnabergoi** [nicolaiarocci/flask-sentinel#7] opened 2015-11-11 22:39 UTC
Hi I try to make it work but i still getting this traceback when im try to to the curl method to get a token

method :  curl -k -X POST -d "client_id=8NuYg0th08PqLU7luqSwmFYfT1PQVQ16sFR5Yui1&grant_type=password&username=test&password=test" https://localhost:5000/oauth/token

log:

Traceback (most recent call last):
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/eve/flaskapp.py", line 929, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask_oauthlib/provider/oauth2.py", line 489, in decorated
    uri, http_method, body, headers, credentials
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/base.py", line 64, in wrapper
    return f(endpoint, uri, *args, **kwargs)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/endpoints/token.py", line 100, in create_token_response
    request, self.default_token_type)
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/grant_types/resource_owner_password_credentials.py", line 101, in create_token_response
    if not self.request_validator.authenticate_client(request):
  File "/home/operador/Documents/idinner/idinnerVE/lib/python2.7/site-packages/flask_oauthlib/provider/oauth2.py", line 607, in authenticate_client
    if client.client_secret != client_secret:
AttributeError: 'Client' object has no attribute 'client_secret'

I have unistall all the package and I try to install again:
pip uninstall oauthlib
pip uninstall Flask-Oauthlib
pip uninstall flask-sentinel

and i install by pip install flask-sentinel getting the succesfull message "Installing collected packages: flask-sentinel, Flask-OAuthlib, oauthlib"

I saw in another post somebody has solved installing again the package but it didnt work for me

Do you know how to solve the problem?

**Comment by nicolaiarocci** [comment] 2015-11-15 18:33
This looks like a duplicate of #5. As you say the other guy solved by simply reinstalling Flask-Oauthlib. Unfortunately I reproduce it.

**Closed by nicolaiarocci** 2015-11-15 18:33 UTC

**Comment by lnabergoi** [comment] 2015-11-15 19:06
So, you can reproduce it, and you close it without solve it?

**Comment by nicolaiarocci** [comment] 2015-11-15 21:11
I meant "cannot" as the "unfortunately" was hinting at. Since it is a duplicate I closed it.
